services:
    minio:
        image: minio/minio:latest
        container_name: minio
        ports:
            - "6969:9000"
            - "6970:9001"
        environment:
            MINIO_ROOT_USER: minioadmin
            MINIO_ROOT_PASSWORD: minioadmin
        volumes:
            - minio_data:/data
        command: server /data --console-address ":9001"

    redis:
        image: redis:latest
        container_name: redis
        ports:
          - "6379:6379"
        volumes:
          - redis_data:/data
        restart: always

    mailpit:
        image: axllent/mailpit
        container_name: mailpit
        ports:
          - "8025:8025"
          - "1025:1025"
        restart: always

volumes:
    minio_data:
    redis_data:
